// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-50_hud_record_16.yaml
//   spec: packets/2-50_hud_record_16.yaml
//   opcode: 0x20032   direction: C2S   size: 16
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Submit a 16-byte HUD record. The sender closes any open panel group, then blits a 16-byte caller-assembled record. Sibling of 2/55 (32B) and 2/58 (24B, priced) in the same in-game panel cluster.
/// Wire layout per <c>packets/2-50_hud_record_16.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHudRecord16
{
    /// <summary>The opcode value for this message. spec: packets/2-50_hud_record_16.yaml</summary>
    public const uint OpcodeId = 0x20032;

    /// <summary>Declared wire size in bytes (spec: packets/2-50_hud_record_16.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHudRecord16&gt;() == 16</c> in a test.</summary>
    public const int Size = 16;

    public RecordBuffer Record;

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/2-50_hud_record_16.yaml</summary>
    [InlineArray(16)]
    public struct RecordBuffer
    {
        private byte _element0;
    }

}
