// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-146_server_ack_echo.yaml
//   spec: packets/2-146_server_ack_echo.yaml
//   opcode: 0x20092   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Reactive echo-reply to S2C 5/146 for PvP zone detection. Echoes back the server-supplied token and a local server/channel identifier.
/// Wire layout per <c>packets/2-146_server_ack_echo.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgServerAckEcho
{
    /// <summary>The opcode value for this message. spec: packets/2-146_server_ack_echo.yaml</summary>
    public const uint OpcodeId = 0x20092;

    /// <summary>Declared wire size in bytes (spec: packets/2-146_server_ack_echo.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgServerAckEcho&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint Token;
    public uint ServerId;
}
