// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-46_item_move.yaml
//   spec: packets/2-46_item_move.yaml
//   opcode: 0x2002e   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client item move / swap -- the shared item-model "move" send used to relocate an item between containers and slots. A fixed 12-byte body carrying an operation/selector and a source/destination container+slot pair plus a context word. This is the SHARED item-move opcode; the storage ("keep") grid uses it to deposit/move items INTO and OUT OF its 60-cell storage grid (the unified destination slot is the storage block base + the cell index).
/// Wire layout per <c>packets/2-46_item_move.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgItemMove
{
    /// <summary>The opcode value for this message. spec: packets/2-46_item_move.yaml</summary>
    public const uint OpcodeId = 0x2002e;

    /// <summary>Declared wire size in bytes (spec: packets/2-46_item_move.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgItemMove&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public byte B0;
    public byte B1;
    public byte B2;
    public byte B3;
    public byte B4;
    public byte B5;
    public Pad0Buffer Pad0;
    public uint Context;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-46_item_move.yaml</summary>
    [InlineArray(2)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
