// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-21_list_select.yaml
//   spec: packets/2-21_list_select.yaml
//   opcode: 0x20015   direction: C2S   size: 2
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Short HUD-list / actor selection action (mode + index). The smallest member of the service-menu family — likely an "open/select" with no extra payload.
/// Wire layout per <c>packets/2-21_list_select.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgListSelect
{
    /// <summary>The opcode value for this message. spec: packets/2-21_list_select.yaml</summary>
    public const uint OpcodeId = 0x20015;

    /// <summary>Declared wire size in bytes (spec: packets/2-21_list_select.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgListSelect&gt;() == 2</c> in a test.</summary>
    public const int Size = 2;

    public byte Mode;
    public byte Index;
}
