// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-114_gated_self_action.yaml
//   spec: packets/2-114_gated_self_action.yaml
//   opcode: 0x20072   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-114_gated_self_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGatedSelfAction114
{
    /// <summary>The opcode value for this message. spec: packets/2-114_gated_self_action.yaml</summary>
    public const uint OpcodeId = 0x20072;

    /// <summary>Declared wire size in bytes (spec: packets/2-114_gated_self_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGatedSelfAction114&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint PlayerField;
}
