// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-145_skill_list_submit.yaml
//   spec: packets/2-145_skill_list_submit.yaml
//   opcode: 0x20091   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Skill-list submit. Submits a confirmed list of skill records from the skill-confirm panel. A u32 record count followed by that many fixed 12-byte records.
/// Wire layout per <c>packets/2-145_skill_list_submit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgSkillListSubmit
{
    /// <summary>The opcode value for this message. spec: packets/2-145_skill_list_submit.yaml</summary>
    public const uint OpcodeId = 0x20091;

    public uint Count;
    public RecordBuffer Record;

    /// <summary>Fixed 12-byte inline buffer (no managed string on the wire). spec: packets/2-145_skill_list_submit.yaml</summary>
    [InlineArray(12)]
    public struct RecordBuffer
    {
        private byte _element0;
    }

}
