// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-19_npc_buy_or_acquire.yaml
//   spec: packets/2-19_npc_buy_or_acquire.yaml
//   opcode: 0x20013   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Buy-or-acquire an item from an NPC merchant via the inventory-driven transaction path (right-click an inventory item against an open NPC shop). This is the request side of the NPC buy/acquire round-trip and the server replies with S2C 4/19 SmsgNpcBuyOrAcquireAck. Reconfirmed in HUD-II Wave 3: the prior "CmsgNpcInteract (generic NPC open)" reading for 2/19 is superseded -- the 12-byte send is the buy/acquire transaction, paired with the already-catalogued 4/19 acknowledgement.
/// Wire layout per <c>packets/2-19_npc_buy_or_acquire.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcBuyOrAcquire
{
    /// <summary>The opcode value for this message. spec: packets/2-19_npc_buy_or_acquire.yaml</summary>
    public const uint OpcodeId = 0x20013;

    /// <summary>Declared wire size in bytes (spec: packets/2-19_npc_buy_or_acquire.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcBuyOrAcquire&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public uint Id;
    public byte Slot;
    public byte SubSel;
    public byte FlagA;
    public byte FlagB;
    public uint Quantity;
}
