// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-24_trade_slot_add.yaml
//   spec: packets/2-24_trade_slot_add.yaml
//   opcode: 0x20018   direction: C2S   size: 20
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client add / update one trade-window slot (offer an item, set a quantity, or set the money total). A 1-byte category selector chooses the meaning of the three 4-byte numeric fields; money is carried as a 64-bit value split across two of them. The server replies with 4/24 TradeSlotUpdate.
/// Wire layout per <c>packets/2-24_trade_slot_add.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgTradeSlotAdd
{
    /// <summary>The opcode value for this message. spec: packets/2-24_trade_slot_add.yaml</summary>
    public const uint OpcodeId = 0x20018;

    /// <summary>Declared wire size in bytes (spec: packets/2-24_trade_slot_add.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgTradeSlotAdd&gt;() == 20</c> in a test.</summary>
    public const int Size = 20;

    public byte Category;
    public byte SlotIndex;
    public Pad0Buffer Pad0;
    public int ValueA;
    public int ValueB;
    public int ValueC;
    public byte FlagA;
    public byte FlagB;
    public byte FlagC;
    public Pad1Buffer Pad1;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-24_trade_slot_add.yaml</summary>
    [InlineArray(2)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 1-byte inline buffer (no managed string on the wire). spec: packets/2-24_trade_slot_add.yaml</summary>
    [InlineArray(1)]
    public struct Pad1Buffer
    {
        private byte _element0;
    }

}
