// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-12_select_target_actor.yaml
//   spec: packets/2-12_select_target_actor.yaml
//   opcode: 0x2000c   direction: C2S   size: 3
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Target / escort-actor selection request. Three contiguous bytes (selection mode, sub-index, escort/party slot index). Sent by the escort/target select handler after it validates the local player's 20-slot escort table.
/// Wire layout per <c>packets/2-12_select_target_actor.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgSelectTargetActor
{
    /// <summary>The opcode value for this message. spec: packets/2-12_select_target_actor.yaml</summary>
    public const uint OpcodeId = 0x2000c;

    /// <summary>Declared wire size in bytes (spec: packets/2-12_select_target_actor.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgSelectTargetActor&gt;() == 3</c> in a test.</summary>
    public const int Size = 3;

    public byte SelectMode;
    public byte SubIndex;
    public byte SlotIndex;
}
