// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-36_party_leave_kick.yaml
//   spec: packets/2-36_party_leave_kick.yaml
//   opcode: 0x20024   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client party leave (self) or kick (expel a member) request. Carries a 1-byte mode selector and a 4-byte actor id. The server replies with 4/36 PartyMemberRemoveResult.
/// Wire layout per <c>packets/2-36_party_leave_kick.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPartyLeaveKick
{
    /// <summary>The opcode value for this message. spec: packets/2-36_party_leave_kick.yaml</summary>
    public const uint OpcodeId = 0x20024;

    /// <summary>Declared wire size in bytes (spec: packets/2-36_party_leave_kick.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPartyLeaveKick&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte Mode;
    public Pad0Buffer Pad0;
    public uint Id;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-36_party_leave_kick.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
