// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-15_pickup_item.yaml
//   spec: packets/2-15_pickup_item.yaml
//   opcode: 0x2000f   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client pickup request. Asks the server to pick up a specific ground item (or coin stack), identified by its world entity key. The server replies with S2C 4/15 SmsgItemWorldPickupAck.
/// Wire layout per <c>packets/2-15_pickup_item.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPickupItem
{
    /// <summary>The opcode value for this message. spec: packets/2-15_pickup_item.yaml</summary>
    public const uint OpcodeId = 0x2000f;

    /// <summary>Declared wire size in bytes (spec: packets/2-15_pickup_item.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPickupItem&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public uint Key;
    public byte Share0;
    public byte Share1;
    public byte Share2;
    public Pad0Buffer Pad0;
    public uint Amount;

    /// <summary>Fixed 1-byte inline buffer (no managed string on the wire). spec: packets/2-15_pickup_item.yaml</summary>
    [InlineArray(1)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
