// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-106_creature_item_tick.yaml
//   spec: packets/2-106_creature_item_tick.yaml
//   opcode: 0x2006a   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Creature-item / effect-tick acknowledgment. A single flag byte (both callers pass the constant 1). A recurring "I'm doing the gated thing now" signal driven by the creature-attached-item effect loop and a UI/map gate.
/// Wire layout per <c>packets/2-106_creature_item_tick.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgCreatureItemTick
{
    /// <summary>The opcode value for this message. spec: packets/2-106_creature_item_tick.yaml</summary>
    public const uint OpcodeId = 0x2006a;

    /// <summary>Declared wire size in bytes (spec: packets/2-106_creature_item_tick.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgCreatureItemTick&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Flag;
}
