// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-128_panel_id_submit.yaml
//   spec: packets/2-128_panel_id_submit.yaml
//   opcode: 0x20080   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-128_panel_id_submit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPanelIdSubmit
{
    /// <summary>The opcode value for this message. spec: packets/2-128_panel_id_submit.yaml</summary>
    public const uint OpcodeId = 0x20080;

    /// <summary>Declared wire size in bytes (spec: packets/2-128_panel_id_submit.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPanelIdSubmit&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint PanelId;
}
