// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-60_letter_request.yaml
//   spec: packets/2-60_letter_request.yaml
//   opcode: 0x2003c   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client request raised by the compact LetterPanel (a small letter-view window). A send-only message carrying an 8-byte fixed body, most likely a letter-id plus a mode/flag -- the open / read / acknowledge round-trip for a single letter. Major 2 is C2S-only, so there is no inbound dispatch slot for this opcode by design.
/// Wire layout per <c>packets/2-60_letter_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgLetterRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-60_letter_request.yaml</summary>
    public const uint OpcodeId = 0x2003c;

    /// <summary>Declared wire size in bytes (spec: packets/2-60_letter_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgLetterRequest&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint LetterId;
    public uint Mode;
}
