// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-142_storage_op.yaml
//   spec: packets/2-142_storage_op.yaml
//   opcode: 0x2008e   direction: C2S   size: 16
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Storage (bank / vault) deposit / withdraw / move operation, sent from the 60-slot storage grid panel that opens off a storage NPC (descriptor KIND 0x9). A fixed 16-byte body carrying a target/select field, an operation byte, and an i64 amount. The client sends only when the amount is greater than zero.
/// Wire layout per <c>packets/2-142_storage_op.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgStorageOp
{
    /// <summary>The opcode value for this message. spec: packets/2-142_storage_op.yaml</summary>
    public const uint OpcodeId = 0x2008e;

    /// <summary>Declared wire size in bytes (spec: packets/2-142_storage_op.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgStorageOp&gt;() == 16</c> in a test.</summary>
    public const int Size = 16;

    public int Target;
    public byte Op;
    public Pad0Buffer Pad0;
    public long Amount;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-142_storage_op.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
