// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-66_relation_toggle.yaml
//   spec: packets/2-66_relation_toggle.yaml
//   opcode: 0x20042   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// A 1-byte toggle / answer from the social confirm (re-ask) panel. The validator is a no-op returning the OK sentinel.
/// Wire layout per <c>packets/2-66_relation_toggle.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgRelationToggle
{
    /// <summary>The opcode value for this message. spec: packets/2-66_relation_toggle.yaml</summary>
    public const uint OpcodeId = 0x20042;

    /// <summary>Declared wire size in bytes (spec: packets/2-66_relation_toggle.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgRelationToggle&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Toggle;
}
