// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-14_drop_item.yaml
//   spec: packets/2-14_drop_item.yaml
//   opcode: 0x2000e   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client drop request. Drops an inventory item (or a coin stack) onto the ground at the local player's feet. The server replies with S2C 4/14 SmsgGroundItemDropAck, which carries the result and spawns the world item.
/// Wire layout per <c>packets/2-14_drop_item.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgDropItem
{
    /// <summary>The opcode value for this message. spec: packets/2-14_drop_item.yaml</summary>
    public const uint OpcodeId = 0x2000e;

    /// <summary>Declared wire size in bytes (spec: packets/2-14_drop_item.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgDropItem&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte Mode;
    public byte Slot;
    public Pad0Buffer Pad0;
    public uint Count;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-14_drop_item.yaml</summary>
    [InlineArray(2)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
