// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-108_npc_locate_request.yaml
//   spec: packets/2-108_npc_locate_request.yaml
//   opcode: 0x2006c   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// NPC search / locate request. Sends the resolved NPC array (npc.arr) record id the player selected, so the server can answer with the NPC's location/region.
/// Wire layout per <c>packets/2-108_npc_locate_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcLocateRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-108_npc_locate_request.yaml</summary>
    public const uint OpcodeId = 0x2006c;

    /// <summary>Declared wire size in bytes (spec: packets/2-108_npc_locate_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcLocateRequest&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint NpcRecordId;
}
