// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-79_actor_target_request.yaml
//   spec: packets/2-79_actor_target_request.yaml
//   opcode: 0x2004f   direction: C2S   size: 16
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// An actor-targeted interaction request — select an entry from a context table, resolve it to a live actor, and send. A leading selector, a table index that maps to an actor id, and resolved-record bytes.
/// Wire layout per <c>packets/2-79_actor_target_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgActorTargetRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-79_actor_target_request.yaml</summary>
    public const uint OpcodeId = 0x2004f;

    /// <summary>Declared wire size in bytes (spec: packets/2-79_actor_target_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgActorTargetRequest&gt;() == 16</c> in a test.</summary>
    public const int Size = 16;

    public byte Selector;
    public Reserved0Buffer Reserved0;
    public byte TableIndex;
    public RecordTailBuffer RecordTail;

    /// <summary>Fixed 7-byte inline buffer (no managed string on the wire). spec: packets/2-79_actor_target_request.yaml</summary>
    [InlineArray(7)]
    public struct Reserved0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 7-byte inline buffer (no managed string on the wire). spec: packets/2-79_actor_target_request.yaml</summary>
    [InlineArray(7)]
    public struct RecordTailBuffer
    {
        private byte _element0;
    }

}
