// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-55_hud_record_32.yaml
//   spec: packets/2-55_hud_record_32.yaml
//   opcode: 0x20037   direction: C2S   size: 32
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Submit a 32-byte HUD record. The sender blits a 32-byte caller-assembled record after the standard list/panel guards. Sibling of 2/50 (16B) and 2/58 (24B, priced) in the same in-game panel cluster.
/// Wire layout per <c>packets/2-55_hud_record_32.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHudRecord32
{
    /// <summary>The opcode value for this message. spec: packets/2-55_hud_record_32.yaml</summary>
    public const uint OpcodeId = 0x20037;

    /// <summary>Declared wire size in bytes (spec: packets/2-55_hud_record_32.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHudRecord32&gt;() == 32</c> in a test.</summary>
    public const int Size = 32;

    public RecordBuffer Record;

    /// <summary>Fixed 32-byte inline buffer (no managed string on the wire). spec: packets/2-55_hud_record_32.yaml</summary>
    [InlineArray(32)]
    public struct RecordBuffer
    {
        private byte _element0;
    }

}
