// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-71_delivery_claim.yaml
//   spec: packets/2-71_delivery_claim.yaml
//   opcode: 0x20047   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client delivery / consignment claim-retrieve. A send-only message carrying a 4-byte fixed body (a single selector or record-id) that retrieves a delivered or consigned item -- or sale proceeds -- from the delivery box. Emitted from the delivery panel's claim-confirm path. Major 2 is C2S-only, so there is no inbound dispatch slot for this opcode by design.
/// Wire layout per <c>packets/2-71_delivery_claim.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgDeliveryClaim
{
    /// <summary>The opcode value for this message. spec: packets/2-71_delivery_claim.yaml</summary>
    public const uint OpcodeId = 0x20047;

    /// <summary>Declared wire size in bytes (spec: packets/2-71_delivery_claim.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgDeliveryClaim&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint Selector;
}
