// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-30_guild_op.yaml
//   spec: packets/2-30_guild_op.yaml
//   opcode: 0x2001e   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Small client guild / relation action primitive. Carries a 4-byte operation code and a 4-byte actor id. The lightweight channel for assorted guild/relation actions; richer guild flows use separate opcodes.
/// Wire layout per <c>packets/2-30_guild_op.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGuildOp
{
    /// <summary>The opcode value for this message. spec: packets/2-30_guild_op.yaml</summary>
    public const uint OpcodeId = 0x2001e;

    /// <summary>Declared wire size in bytes (spec: packets/2-30_guild_op.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGuildOp&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint Op;
    public uint Id;
}
