// <auto-generated>
//   Generated by the packet-codegen skill from packets/login.yaml
//   spec: packets/login.yaml
//   opcode: 0x10004   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/login.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgLoginCredential
{
    /// <summary>The opcode value for this message. spec: packets/login.yaml</summary>
    public const uint OpcodeId = 0x10004;

    public byte SubOpcode;
}
