// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-152_quest_row_request.yaml
//   spec: packets/2-152_quest_row_request.yaml
//   opcode: 0x20098   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client per-row request raised by the quest-log window's list rows -- the "request detail / claim" round-trip for a quest row. Built by a generic two-u32 sender (major 2 / minor 152) that writes the header and appends exactly two u32 args. The QuestPanel is the sole consumer (the prior ProductPanel-paging overload is resolved away). Send-only; the quest result returns on the 5/68 / 5/73 push channels.
/// Wire layout per <c>packets/2-152_quest_row_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgQuestRowRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-152_quest_row_request.yaml</summary>
    public const uint OpcodeId = 0x20098;

    /// <summary>Declared wire size in bytes (spec: packets/2-152_quest_row_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgQuestRowRequest&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint Arg1;
    public uint Arg2;
}
