// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-81_guild_diplomacy_declare.yaml
//   spec: packets/2-81_guild_diplomacy_declare.yaml
//   opcode: 0x20051   direction: C2S   size: 18
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client guild-diplomacy / brood-war declaration request, sent from the guild-relations list window (BroodWarListPanel). A fixed 18-byte body carrying a leading action/state byte and a 17-byte CP949 target guild name. The same body shape also serves the open / relation-list request on this panel; which numeric action value is declare-war vs declare-ally vs list-request is capture-pending.
/// Wire layout per <c>packets/2-81_guild_diplomacy_declare.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGuildDiplomacyDeclare
{
    /// <summary>The opcode value for this message. spec: packets/2-81_guild_diplomacy_declare.yaml</summary>
    public const uint OpcodeId = 0x20051;

    /// <summary>Declared wire size in bytes (spec: packets/2-81_guild_diplomacy_declare.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGuildDiplomacyDeclare&gt;() == 18</c> in a test.</summary>
    public const int Size = 18;

    public byte Action;
    public GuildNameBuffer GuildName;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-81_guild_diplomacy_declare.yaml</summary>
    [InlineArray(17)]
    public struct GuildNameBuffer
    {
        private byte _element0;
    }

}
