// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-141_craft_submit.yaml
//   spec: packets/2-141_craft_submit.yaml
//   opcode: 0x2008d   direction: C2S   size: 76
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Crafting/production recipe submission. Carries 14 material slot values, 4 extra parameter dwords, and the NPC actor index.
/// Wire layout per <c>packets/2-141_craft_submit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgCraftSubmit
{
    /// <summary>The opcode value for this message. spec: packets/2-141_craft_submit.yaml</summary>
    public const uint OpcodeId = 0x2008d;

    /// <summary>Declared wire size in bytes (spec: packets/2-141_craft_submit.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgCraftSubmit&gt;() == 76</c> in a test.</summary>
    public const int Size = 76;

    public MaterialSlotsBuffer MaterialSlots;
    public ExtraParamsBuffer ExtraParams;
    public byte NpcActorIndex;
    public PaddingBuffer Padding;

    /// <summary>Fixed 56-byte inline buffer (no managed string on the wire). spec: packets/2-141_craft_submit.yaml</summary>
    [InlineArray(56)]
    public struct MaterialSlotsBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/2-141_craft_submit.yaml</summary>
    [InlineArray(16)]
    public struct ExtraParamsBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-141_craft_submit.yaml</summary>
    [InlineArray(3)]
    public struct PaddingBuffer
    {
        private byte _element0;
    }

}
