// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-8_hotbar_sync.yaml
//   spec: packets/2-8_hotbar_sync.yaml
//   opcode: 0x20008   direction: C2S   size: 241
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-8_hotbar_sync.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHotbarSync
{
    /// <summary>The opcode value for this message. spec: packets/2-8_hotbar_sync.yaml</summary>
    public const uint OpcodeId = 0x20008;

    /// <summary>Declared wire size in bytes (spec: packets/2-8_hotbar_sync.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHotbarSync&gt;() == 241</c> in a test.</summary>
    public const int Size = 241;

    public byte Count;
    public SlotIndicesBuffer SlotIndices;

    /// <summary>Fixed 240-byte inline buffer (no managed string on the wire). spec: packets/2-8_hotbar_sync.yaml</summary>
    [InlineArray(240)]
    public struct SlotIndicesBuffer
    {
        private byte _element0;
    }

}
