// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-4_scene_entity_update.yaml
//   spec: packets/3-4_scene_entity_update.yaml
//   opcode: 0x30004   direction: S2C   size: variable
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using MartialHeroes.Network.Protocol.Opcodes;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Variable-length scene/entity/char-slot update (3/4). This struct models the FIXED 3-byte header
/// only. The variable tail (per-slot records driven by SlotMask) is decoded by the caller.
/// Wire layout per <c>packets/3-4_scene_entity_update.yaml</c>.
/// </summary>
[PacketOpcode(3, 4)] // spec: Docs/RE/packets/3-4_scene_entity_update.yaml (opcode 3/4 = 0x30004)
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgSceneEntityUpdate
{
    /// <summary>The opcode value for this message. spec: packets/3-4_scene_entity_update.yaml</summary>
    public const uint OpcodeId = 0x30004;

    /// <summary>Size of the fixed header in bytes. spec: packets/3-4_scene_entity_update.yaml (3-byte header).</summary>
    public const int HeaderSize = 3; // spec: Docs/RE/packets/3-4_scene_entity_update.yaml

    public byte ServerId;
    public byte ChannelId;
    public byte SlotMask;
}
