// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-4_scene_entity_update.yaml
//   spec: packets/3-4_scene_entity_update.yaml
//   opcode: 0x30004   direction: S2C   size: variable
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/3-4_scene_entity_update.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgSceneEntityUpdate
{
    /// <summary>The opcode value for this message. spec: packets/3-4_scene_entity_update.yaml</summary>
    public const uint OpcodeId = 0x30004;

    public byte ServerId;
    public byte ChannelId;
    public byte SlotMask;
}
