// <auto-generated>
//   Generated by the packet-codegen skill from packets/1-19_srv_billing_expiry_notice.yaml
//   spec: packets/1-19_srv_billing_expiry_notice.yaml
//   opcode: 0x10013   direction: S2C   size: 22
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/1-19_srv_billing_expiry_notice.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgSrvBillingExpiryNotice
{
    /// <summary>The opcode value for this message. spec: packets/1-19_srv_billing_expiry_notice.yaml</summary>
    public const uint OpcodeId = 0x10013;

    /// <summary>Declared wire size in bytes (spec: packets/1-19_srv_billing_expiry_notice.yaml). Verify with <c>Unsafe.SizeOf&lt;SmsgSrvBillingExpiryNotice&gt;() == 22</c> in a test.</summary>
    public const int Size = 22;

    public byte Dummy;
    public byte NoticeType;
    public SubscriptionCodeBuffer SubscriptionCode;
    public uint TimeLeft;

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/1-19_srv_billing_expiry_notice.yaml</summary>
    [InlineArray(16)]
    public struct SubscriptionCodeBuffer
    {
        private byte _element0;
    }

}
