// <auto-generated>
//   Generated by the packet-codegen skill from packets/1-20_srv_letter_received.yaml
//   spec: packets/1-20_srv_letter_received.yaml
//   opcode: 0x10014   direction: S2C   size: variable
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/1-20_srv_letter_received.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgSrvLetterReceived
{
    /// <summary>The opcode value for this message. spec: packets/1-20_srv_letter_received.yaml</summary>
    public const uint OpcodeId = 0x10014;

    public uint LetterId;
    public SenderBuffer Sender;
    public Pad0Buffer Pad0;
    public uint LetterType;
    public uint AttachmentGold;
    public uint AttachmentItemId;
    public uint StatusFlags;
    public DateStringBuffer DateString;
    public SubjectStringBuffer SubjectString;
    public ReservedBuffer Reserved;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/1-20_srv_letter_received.yaml</summary>
    [InlineArray(17)]
    public struct SenderBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/1-20_srv_letter_received.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/1-20_srv_letter_received.yaml</summary>
    [InlineArray(17)]
    public struct DateStringBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/1-20_srv_letter_received.yaml</summary>
    [InlineArray(17)]
    public struct SubjectStringBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/1-20_srv_letter_received.yaml</summary>
    [InlineArray(2)]
    public struct ReservedBuffer
    {
        private byte _element0;
    }

}
