// <auto-generated>
//   Generated by the packet-codegen skill from packets/cmsg_char_select.yaml
//   spec: packets/cmsg_char_select.yaml
//   opcode: 0x10007   direction: C2S   size: 2
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/cmsg_char_select.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgManageCharacter
{
    /// <summary>The opcode value for this message. spec: packets/cmsg_char_select.yaml</summary>
    public const uint OpcodeId = 0x10007;

    /// <summary>Declared wire size in bytes (spec: packets/cmsg_char_select.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgManageCharacter&gt;() == 2</c> in a test.</summary>
    public const int Size = 2;

    public byte SlotIndex;
    public byte Mode;
}
