// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-21_chat_channel.yaml
//   spec: packets/3-21_chat_channel.yaml
//   opcode: 0x30015   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client general / channel chat. A 56-byte context header (sender + channel/scope metadata), followed by a length-prefixed text body. Channel routing is selected inside the header.
/// Wire layout per <c>packets/3-21_chat_channel.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgChatChannel
{
    /// <summary>The opcode value for this message. spec: packets/3-21_chat_channel.yaml</summary>
    public const uint OpcodeId = 0x30015;

    public HeaderPrefixBuffer HeaderPrefix;
    public uint ChannelSelector;
    public HeaderRestBuffer HeaderRest;

    /// <summary>Fixed 4-byte inline buffer (no managed string on the wire). spec: packets/3-21_chat_channel.yaml</summary>
    [InlineArray(4)]
    public struct HeaderPrefixBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 48-byte inline buffer (no managed string on the wire). spec: packets/3-21_chat_channel.yaml</summary>
    [InlineArray(48)]
    public struct HeaderRestBuffer
    {
        private byte _element0;
    }

}
