// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-13_char_status_update.yaml
//   spec: packets/3-13_char_status_update.yaml
//   opcode: 0x3000d   direction: S2C   size: 19
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using MartialHeroes.Network.Protocol.Core.Opcodes;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Wire layout per <c>packets/3-13_char_status_update.yaml</c>.
/// </summary>
[PacketOpcode(3, 13)] // spec: Docs/RE/packets/3-13_char_status_update.yaml (opcode 3/13 = 0x3000d)
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgCharStatusUpdate
{
    /// <summary>The opcode value for this message. spec: packets/3-13_char_status_update.yaml</summary>
    public const uint OpcodeId = 0x3000d;

    /// <summary>Declared wire size in bytes (spec: packets/3-13_char_status_update.yaml). Verify with <c>Unsafe.SizeOf&lt;SmsgCharStatusUpdate&gt;() == 19</c> in a test.</summary>
    public const int Size = 19;

    public byte Result;
    public byte ErrorCode;
    public NameBuffer Name;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/3-13_char_status_update.yaml</summary>
    [InlineArray(17)]
    public struct NameBuffer
    {
        private byte _element0;
    }

}
