// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-8_shop_page_update.yaml
//   spec: packets/3-8_shop_page_update.yaml
//   opcode: 0x30008   direction: S2C   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using MartialHeroes.Network.Protocol.Core.Opcodes;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Inbound money/gold refresh for the product/crafting panel. The handler reads exactly one u32 (the player's current gold), stores it to player-state, and triggers a repaint of the active product panel. It carries NO recipe grid and NO page array -- the recipe list is populated from a client-cached vector filled elsewhere (area/NPC load); 3/8 only re-drives the money value and the panel repaint.
/// Wire layout per <c>packets/3-8_shop_page_update.yaml</c>.
/// </summary>
[PacketOpcode(3, 8)] // spec: Docs/RE/packets/3-8_shop_page_update.yaml (opcode 3/8 = 0x30008)
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgShopPageUpdate
{
    /// <summary>The opcode value for this message. spec: packets/3-8_shop_page_update.yaml</summary>
    public const uint OpcodeId = 0x30008;

    /// <summary>Declared wire size in bytes (spec: packets/3-8_shop_page_update.yaml). Verify with <c>Unsafe.SizeOf&lt;SmsgShopPageUpdate&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint Money;
}
