// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-14_char_spawn_response.yaml
//   spec: packets/3-14_char_spawn_response.yaml
//   opcode: 0x3000e   direction: S2C   size: 16
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/3-14_char_spawn_response.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgCharSpawnResponse
{
    /// <summary>The opcode value for this message. spec: packets/3-14_char_spawn_response.yaml</summary>
    public const uint OpcodeId = 0x3000e;

    /// <summary>Declared wire size in bytes (spec: packets/3-14_char_spawn_response.yaml). Verify with <c>Unsafe.SizeOf&lt;SmsgCharSpawnResponse&gt;() == 16</c> in a test.</summary>
    public const int Size = 16;

    public byte Result;
    public byte Subtype;
    public PadBuffer Pad;
    public uint ValA;
    public uint ValB;
    public uint ValC;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/3-14_char_spawn_response.yaml</summary>
    [InlineArray(2)]
    public struct PadBuffer
    {
        private byte _element0;
    }

}
