// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-23_char_select_status_update.yaml
//   spec: packets/3-23_char_select_status_update.yaml
//   opcode: 0x30017   direction: S2C   size: 28
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/3-23_char_select_status_update.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgCharSelectStatusUpdate
{
    /// <summary>The opcode value for this message. spec: packets/3-23_char_select_status_update.yaml</summary>
    public const uint OpcodeId = 0x30017;

    /// <summary>Declared wire size in bytes (spec: packets/3-23_char_select_status_update.yaml). Verify with <c>Unsafe.SizeOf&lt;SmsgCharSelectStatusUpdate&gt;() == 28</c> in a test.</summary>
    public const int Size = 28;

    public byte HasCustomText;
    public byte StatusCode;
    public Pad0Buffer Pad0;
    public CharacterNameBuffer CharacterName;
    public byte StatusValue;
    public byte Level;
    public byte Padding;

    /// <summary>Fixed 6-byte inline buffer (no managed string on the wire). spec: packets/3-23_char_select_status_update.yaml</summary>
    [InlineArray(6)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/3-23_char_select_status_update.yaml</summary>
    [InlineArray(17)]
    public struct CharacterNameBuffer
    {
        private byte _element0;
    }

}
