// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-1_character_list.yaml
//   spec: packets/3-1_character_list.yaml
//   opcode: 0x30001   direction: S2C   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Character-select list. A 3-byte header with a slot bitmask, followed by one 981-byte slot record per populated slot. The handler loops EXACTLY 5 slot indices (the account character-slot count) and reads a record per set bit. Each slot record is an 880-byte SpawnDescriptor + a 96-byte stat block + a flag + a timestamp. The descriptor drives the slot's rendered appearance (skin/skeleton/outfit) -- a list slot shows the REAL character, not a placeholder.
/// Wire layout per <c>packets/3-1_character_list.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgCharacterList
{
    /// <summary>The opcode value for this message. spec: packets/3-1_character_list.yaml</summary>
    public const uint OpcodeId = 0x30001;

    public byte ServerId;
    public byte ChannelId;
    public byte SlotMask;
}
