// <auto-generated>
//   Generated by the packet-codegen skill from packets/3-50000_gm_chat_message.yaml
//   spec: packets/3-50000_gm_chat_message.yaml
//   opcode: 0x3c350   direction: S2C   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/3-50000_gm_chat_message.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct SmsgGmChatMessage
{
    /// <summary>The opcode value for this message. spec: packets/3-50000_gm_chat_message.yaml</summary>
    public const uint OpcodeId = 0x3c350;

    public byte ChatType;
    public uint TextLength;
}
