using System;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MartialHeroes.Shared.Kernel.Generators;

[Generator]
public sealed class StronglyTypedIdGenerator : IIncrementalGenerator
{
    private const string AttributeFqn = "MartialHeroes.Shared.Kernel.StronglyTypedIdAttribute";

    private const string AttributeSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace MartialHeroes.Shared.Kernel
        {
            /// <summary>
            /// Marks a positional <c>readonly partial record struct</c> as a strongly-typed id. The
            /// generator adds <see cref="System.IComparable{T}"/>, a <c>None</c> zero-sentinel, and a
            /// <c>Prefix(Value)</c> <c>ToString()</c>. The wrapped value's name comes from the record's
            /// primary-constructor parameter; the prefix defaults to the type name without a trailing "Id".
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            internal sealed class StronglyTypedIdAttribute : System.Attribute
            {
                /// <summary>Optional override for the <c>ToString()</c> prefix.</summary>
                /// <param name="name">The prefix to use, or null to derive it from the type name.</param>
                public StronglyTypedIdAttribute(string? name = null) => Name = name;

                /// <summary>The <c>ToString()</c> prefix override, or null to derive it from the type name.</summary>
                public string? Name { get; }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("StronglyTypedIdAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFqn,
            static (_, _) => true,
            static (ctx, _) => Extract(ctx));

        context.RegisterSourceOutput(
            models.Where(static m => m is not null),
            static (spc, model) => Emit(spc, model!.Value));
    }


    private static IdModel? Extract(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
            return null;
        if (type.TypeKind != TypeKind.Struct || !type.IsRecord)
            return null;

        IMethodSymbol? primary = null;
        foreach (var ctor in type.InstanceConstructors)
            if (ctor.Parameters.Length == 1)
            {
                primary = ctor;
                break;
            }

        if (primary is null)
            return null;

        var valueName = primary.Parameters[0].Name;
        var prefix = DerivePrefix(type, ctx.Attributes);
        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        return new IdModel(ns, type.Name, valueName, prefix);
    }

    private static string DerivePrefix(INamedTypeSymbol type, ImmutableArray<AttributeData> attrs)
    {
        foreach (var a in attrs)
            if (a.ConstructorArguments.Length == 1 &&
                a.ConstructorArguments[0].Value is string s && s.Length > 0)
                return s;

        var n = type.Name;
        return n.Length > 2 && n.EndsWith("Id", StringComparison.Ordinal)
            ? n.Substring(0, n.Length - 2)
            : n;
    }


    private static void Emit(SourceProductionContext spc, IdModel m)
    {
        var hasNs = m.Namespace.Length > 0;
        var pad = hasNs ? "    " : string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("//   Generated by StronglyTypedIdGenerator — DO NOT EDIT (regenerated each build).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (hasNs)
        {
            sb.Append("namespace ").AppendLine(m.Namespace);
            sb.AppendLine("{");
        }

        sb.Append(pad).Append("partial record struct ").Append(m.TypeName)
            .Append(" : System.IComparable<").Append(m.TypeName).AppendLine(">");
        sb.Append(pad).AppendLine("{");

        sb.Append(pad).AppendLine("    /// <summary>The zero/absent sentinel for this id.</summary>");
        sb.Append(pad).Append("    public static readonly ").Append(m.TypeName).AppendLine(" None = new(default);");
        sb.AppendLine();

        sb.Append(pad).AppendLine("    /// <inheritdoc/>");
        sb.Append(pad).Append("    public int CompareTo(").Append(m.TypeName).Append(" other) => ")
            .Append(m.ValueName).Append(".CompareTo(other.").Append(m.ValueName).AppendLine(");");
        sb.AppendLine();

        sb.Append(pad).AppendLine("    /// <inheritdoc/>");
        sb.Append(pad).Append("    public override string ToString() => $\"")
            .Append(m.Prefix).Append("({").Append(m.ValueName).Append("})\";").AppendLine();

        sb.Append(pad).AppendLine("}");
        if (hasNs)
            sb.AppendLine("}");

        spc.AddSource(m.TypeName + ".StronglyTypedId.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly record struct IdModel(string Namespace, string TypeName, string ValueName, string Prefix);
}