// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-120_event_item_list_submit.yaml
//   spec: packets/2-120_event_item_list_submit.yaml
//   opcode: 0x20078   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Event-item list submit. Raised when the user confirms an event-item panel holding a list of selected event items. A one-byte flag, a u32 record count, then that many fixed 12-byte records.
/// Wire layout per <c>packets/2-120_event_item_list_submit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgEventItemListSubmit
{
    /// <summary>The opcode value for this message. spec: packets/2-120_event_item_list_submit.yaml</summary>
    public const uint OpcodeId = 0x20078;

    public byte Flag;
    public uint Count;
    public uint RecordId;
    public byte RecordA;
    public byte RecordB;
    public RecordPadBuffer RecordPad;

    /// <summary>Fixed 6-byte inline buffer (no managed string on the wire). spec: packets/2-120_event_item_list_submit.yaml</summary>
    [InlineArray(6)]
    public struct RecordPadBuffer
    {
        private byte _element0;
    }

}
