// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-139_auto_interact.yaml
//   spec: packets/2-139_auto_interact.yaml
//   opcode: 0x2008b   direction: C2S   size: 28
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Proximity-based auto-interaction with nearby NPC. Sent when the client triggers an automatic interaction based on proximity to an NPC actor.
/// Wire layout per <c>packets/2-139_auto_interact.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgAutoInteract
{
    /// <summary>The opcode value for this message. spec: packets/2-139_auto_interact.yaml</summary>
    public const uint OpcodeId = 0x2008b;

    // WARNING: spec size=28 but summed field widths=32. Reconcile the spec.
    /// <summary>Declared wire size in bytes (spec: packets/2-139_auto_interact.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgAutoInteract&gt;() == 32</c> in a test.</summary>
    public const int Size = 32;

    public byte InteractionType;
    public byte SlotIndex;
    public byte ChannelByte;
    public byte Reserved0;
    public uint TargetActorId;
    public ContextBuffer Context;

    /// <summary>Fixed 24-byte inline buffer (no managed string on the wire). spec: packets/2-139_auto_interact.yaml</summary>
    [InlineArray(24)]
    public struct ContextBuffer
    {
        private byte _element0;
    }

}
