// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-48_submit_id.yaml
//   spec: packets/2-48_submit_id.yaml
//   opcode: 0x20030   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Confirm / submit a single u32 id selected from a HUD list. The simplest member of the HUD record-submit family.
/// Wire layout per <c>packets/2-48_submit_id.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgSubmitId
{
    /// <summary>The opcode value for this message. spec: packets/2-48_submit_id.yaml</summary>
    public const uint OpcodeId = 0x20030;

    /// <summary>Declared wire size in bytes (spec: packets/2-48_submit_id.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgSubmitId&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint Id;
}
