// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-40_submit_record.yaml
//   spec: packets/2-40_submit_record.yaml
//   opcode: 0x20028   direction: C2S   size: 72
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Submit a full multi-field record selected from a HUD list. A fixed 72-byte opaque record; the only field a pre-flight validator reads is a u8 selector/index at body offset 0x44.
/// Wire layout per <c>packets/2-40_submit_record.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgSubmitRecord
{
    /// <summary>The opcode value for this message. spec: packets/2-40_submit_record.yaml</summary>
    public const uint OpcodeId = 0x20028;

    /// <summary>Declared wire size in bytes (spec: packets/2-40_submit_record.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgSubmitRecord&gt;() == 72</c> in a test.</summary>
    public const int Size = 72;

    public RecordBodyBuffer RecordBody;
    public byte SelectorIndex;
    public TailBuffer Tail;

    /// <summary>Fixed 68-byte inline buffer (no managed string on the wire). spec: packets/2-40_submit_record.yaml</summary>
    [InlineArray(68)]
    public struct RecordBodyBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-40_submit_record.yaml</summary>
    [InlineArray(3)]
    public struct TailBuffer
    {
        private byte _element0;
    }

}
