// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-63_relation_named_action.yaml
//   spec: packets/2-63_relation_named_action.yaml
//   opcode: 0x2003f   direction: C2S   size: 17
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// A name-targeted party/guild action (invite-to / promote-within a named target), gated by class rank and gold. A 16-byte character name plus a mode/flag byte.
/// Wire layout per <c>packets/2-63_relation_named_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgRelationNamedAction
{
    /// <summary>The opcode value for this message. spec: packets/2-63_relation_named_action.yaml</summary>
    public const uint OpcodeId = 0x2003f;

    /// <summary>Declared wire size in bytes (spec: packets/2-63_relation_named_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgRelationNamedAction&gt;() == 17</c> in a test.</summary>
    public const int Size = 17;

    public NameBuffer Name;
    public byte Mode;

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/2-63_relation_named_action.yaml</summary>
    [InlineArray(16)]
    public struct NameBuffer
    {
        private byte _element0;
    }

}
