// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-3_dialog_response.yaml
//   spec: packets/2-3_dialog_response.yaml
//   opcode: 0x20003   direction: C2S   size: 2
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-3_dialog_response.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgDialogResponse
{
    /// <summary>The opcode value for this message. spec: packets/2-3_dialog_response.yaml</summary>
    public const uint OpcodeId = 0x20003;

    /// <summary>Declared wire size in bytes (spec: packets/2-3_dialog_response.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgDialogResponse&gt;() == 2</c> in a test.</summary>
    public const int Size = 2;

    public ushort ResponseCode;
}
