// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-29_stat_allocate.yaml
//   spec: packets/2-29_stat_allocate.yaml
//   opcode: 0x2001d   direction: C2S   size: 20
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client stat-point allocation request. Carries the five primary stats as ABSOLUTE target values (not deltas), in the order STR, INT, AGI, DEX, CON. Sent by the character/stat window's Apply action. The server answers with the 4/29 stat-update ack.
/// Wire layout per <c>packets/2-29_stat_allocate.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgStatAllocate
{
    /// <summary>The opcode value for this message. spec: packets/2-29_stat_allocate.yaml</summary>
    public const uint OpcodeId = 0x2001d;

    /// <summary>Declared wire size in bytes (spec: packets/2-29_stat_allocate.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgStatAllocate&gt;() == 20</c> in a test.</summary>
    public const int Size = 20;

    public uint Str;
    public uint Int;
    public uint Agi;
    public uint Dex;
    public uint Con;
}
