// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-2_portal_travel.yaml
//   spec: packets/2-2_portal_travel.yaml
//   opcode: 0x20002   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Portal / map-transition (teleport) travel request. A single u32 destination/portal selector. Auto-emitted (not from a button) when the local-player state-sync path detects the player is standing on a portal trigger and a cooldown has elapsed.
/// Wire layout per <c>packets/2-2_portal_travel.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPortalTravel
{
    /// <summary>The opcode value for this message. spec: packets/2-2_portal_travel.yaml</summary>
    public const uint OpcodeId = 0x20002;

    /// <summary>Declared wire size in bytes (spec: packets/2-2_portal_travel.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPortalTravel&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint TargetId;
}
