// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-28_quest_action.yaml
//   spec: packets/2-28_quest_action.yaml
//   opcode: 0x2001c   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client quest action request. A single send-only message that carries the player's quest-flow command (accept / proceed / give-up), chosen by a sub-action selector. The body is a FIXED 12 bytes (the send site always appends 0xC), NOT variable. Major 2 is C2S-only, so this message has no inbound dispatch slot by design and the server answers through unrelated push channels (5/68 quest list, 5/73 quest complete).
/// Wire layout per <c>packets/2-28_quest_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgQuestAction
{
    /// <summary>The opcode value for this message. spec: packets/2-28_quest_action.yaml</summary>
    public const uint OpcodeId = 0x2001c;

    /// <summary>Declared wire size in bytes (spec: packets/2-28_quest_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgQuestAction&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public uint SubAction;
    public uint QuestId;
    public uint ParamA;
}
