// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-99_action_toggle.yaml
//   spec: packets/2-99_action_toggle.yaml
//   opcode: 0x20063   direction: C2S   size: 3
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Small stance/action toggle (window command) carrying an action code, a category byte, and a local-player condition flag. Two sibling builders distinguish two related command families sharing the same 3-byte shape.
/// Wire layout per <c>packets/2-99_action_toggle.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgActionToggle
{
    /// <summary>The opcode value for this message. spec: packets/2-99_action_toggle.yaml</summary>
    public const uint OpcodeId = 0x20063;

    /// <summary>Declared wire size in bytes (spec: packets/2-99_action_toggle.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgActionToggle&gt;() == 3</c> in a test.</summary>
    public const int Size = 3;

    public byte ActionCode;
    public byte Category;
    public byte LocalFlag;
}
