// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-82_gift_present.yaml
//   spec: packets/2-82_gift_present.yaml
//   opcode: 0x20052   direction: C2S   size: 28
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Send a gift/present to another player. Carries a gift id or proxy value, a UI parameter, and a 17-byte CP949 friend name with trailing padding.
/// Wire layout per <c>packets/2-82_gift_present.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGiftPresent
{
    /// <summary>The opcode value for this message. spec: packets/2-82_gift_present.yaml</summary>
    public const uint OpcodeId = 0x20052;

    /// <summary>Declared wire size in bytes (spec: packets/2-82_gift_present.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGiftPresent&gt;() == 28</c> in a test.</summary>
    public const int Size = 28;

    public uint GiftIdOrProxy;
    public uint ParamFromUI;
    public FriendNameBuffer FriendName;
    public PaddingBuffer Padding;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-82_gift_present.yaml</summary>
    [InlineArray(17)]
    public struct FriendNameBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-82_gift_present.yaml</summary>
    [InlineArray(3)]
    public struct PaddingBuffer
    {
        private byte _element0;
    }

}
