// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-135_npc_search_by_name.yaml
//   spec: packets/2-135_npc_search_by_name.yaml
//   opcode: 0x20087   direction: C2S   size: 21
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Name-only NPC search request. Carries a 20-byte CP949 search name and a trailing pad byte.
/// Wire layout per <c>packets/2-135_npc_search_by_name.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcSearchByName
{
    /// <summary>The opcode value for this message. spec: packets/2-135_npc_search_by_name.yaml</summary>
    public const uint OpcodeId = 0x20087;

    /// <summary>Declared wire size in bytes (spec: packets/2-135_npc_search_by_name.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcSearchByName&gt;() == 21</c> in a test.</summary>
    public const int Size = 21;

    public SearchNameBuffer SearchName;
    public byte Pad;

    /// <summary>Fixed 20-byte inline buffer (no managed string on the wire). spec: packets/2-135_npc_search_by_name.yaml</summary>
    [InlineArray(20)]
    public struct SearchNameBuffer
    {
        private byte _element0;
    }

}
