// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-49_friend_add_remove.yaml
//   spec: packets/2-49_friend_add_remove.yaml
//   opcode: 0x20031   direction: C2S   size: 19
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client add or remove a friend, by name. One send-only message that serves BOTH operations -- a leading tag byte selects add (0) vs cut/remove (1) -- carrying a 16-byte CP949 friend name. Issued from the friend window's add-name and cut-name text fields after the typed name is committed.
/// Wire layout per <c>packets/2-49_friend_add_remove.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgFriendAddRemove
{
    /// <summary>The opcode value for this message. spec: packets/2-49_friend_add_remove.yaml</summary>
    public const uint OpcodeId = 0x20031;

    /// <summary>Declared wire size in bytes (spec: packets/2-49_friend_add_remove.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgFriendAddRemove&gt;() == 19</c> in a test.</summary>
    public const int Size = 19;

    public byte Tag;
    public byte Index;
    public NameBuffer Name;
    public Pad0Buffer Pad0;

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/2-49_friend_add_remove.yaml</summary>
    [InlineArray(16)]
    public struct NameBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 1-byte inline buffer (no managed string on the wire). spec: packets/2-49_friend_add_remove.yaml</summary>
    [InlineArray(1)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
