// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-6_stance_swap.yaml
//   spec: packets/2-6_stance_swap.yaml
//   opcode: 0x20006   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Combat stance/weapon mode toggle. Client-side throttled at 2000ms. Carries the desired stance id, a flag byte, padding, and an optional target actor id used for duel-forced transitions.
/// Wire layout per <c>packets/2-6_stance_swap.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgStanceSwap
{
    /// <summary>The opcode value for this message. spec: packets/2-6_stance_swap.yaml</summary>
    public const uint OpcodeId = 0x20006;

    /// <summary>Declared wire size in bytes (spec: packets/2-6_stance_swap.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgStanceSwap&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte StanceId;
    public byte Flag;
    public ushort Reserved0;
    public uint TargetActorId;
}
