// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-25_trade_confirm.yaml
//   spec: packets/2-25_trade_confirm.yaml
//   opcode: 0x20019   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client confirm / cancel a trade and (on confirm) re-transmit its own-side offer as a manifest. A 2-byte header (mode + flag) is followed by one 4-byte record per occupied own-side trade slot, up to 40. This is NOT a flat 2-byte packet.
/// Wire layout per <c>packets/2-25_trade_confirm.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgTradeConfirm
{
    /// <summary>The opcode value for this message. spec: packets/2-25_trade_confirm.yaml</summary>
    public const uint OpcodeId = 0x20019;

    public byte Mode;
    public byte Flag;
}
