// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-115_shop_buy.yaml
//   spec: packets/2-115_shop_buy.yaml
//   opcode: 0x20073   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Buy / order commit from the NPC storefront list (the item-shop vendor panel). The send carries the current shop NPC id and the selected storefront row (encoded as the row index times two). Reconfirmed in HUD-II Wave 3: the body is a FIXED 8 bytes (the earlier 'var' reading is corrected). The server replies on the NPC buy/acquire / item-shop result family (S2C 4/19, 4/113) and the balance push 4/115.
/// Wire layout per <c>packets/2-115_shop_buy.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgShopBuy
{
    /// <summary>The opcode value for this message. spec: packets/2-115_shop_buy.yaml</summary>
    public const uint OpcodeId = 0x20073;

    /// <summary>Declared wire size in bytes (spec: packets/2-115_shop_buy.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgShopBuy&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint NpcId;
    public uint RowX2;
}
