// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-134_npc_search_by_id.yaml
//   spec: packets/2-134_npc_search_by_id.yaml
//   opcode: 0x20086   direction: C2S   size: 24
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Dual-mode NPC search (by ID or by name string). When SearchId is nonzero the server looks up by NPC id; when SearchId is zero the server falls back to the CP949 name filter.
/// Wire layout per <c>packets/2-134_npc_search_by_id.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcSearchById
{
    /// <summary>The opcode value for this message. spec: packets/2-134_npc_search_by_id.yaml</summary>
    public const uint OpcodeId = 0x20086;

    /// <summary>Declared wire size in bytes (spec: packets/2-134_npc_search_by_id.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcSearchById&gt;() == 24</c> in a test.</summary>
    public const int Size = 24;

    public uint SearchId;
    public NameFilterBuffer NameFilter;
    public PaddingBuffer Padding;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-134_npc_search_by_id.yaml</summary>
    [InlineArray(17)]
    public struct NameFilterBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-134_npc_search_by_id.yaml</summary>
    [InlineArray(3)]
    public struct PaddingBuffer
    {
        private byte _element0;
    }

}
