// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-70_carrier_pigeon_send.yaml
//   spec: packets/2-70_carrier_pigeon_send.yaml
//   opcode: 0x20046   direction: C2S   size: 132
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-70_carrier_pigeon_send.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgCarrierPigeonSend
{
    /// <summary>The opcode value for this message. spec: packets/2-70_carrier_pigeon_send.yaml</summary>
    public const uint OpcodeId = 0x20046;

    /// <summary>Declared wire size in bytes (spec: packets/2-70_carrier_pigeon_send.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgCarrierPigeonSend&gt;() == 132</c> in a test.</summary>
    public const int Size = 132;

    public byte SendMode;
    public RecipientBuffer Recipient;
    public Pad12Buffer Pad12;
    public uint MoneyLow;
    public uint MoneyHigh;
    public ItemHandlesBuffer ItemHandles;
    public MessageBodyBuffer MessageBody;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-70_carrier_pigeon_send.yaml</summary>
    [InlineArray(17)]
    public struct RecipientBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-70_carrier_pigeon_send.yaml</summary>
    [InlineArray(2)]
    public struct Pad12Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 20-byte inline buffer (no managed string on the wire). spec: packets/2-70_carrier_pigeon_send.yaml</summary>
    [InlineArray(20)]
    public struct ItemHandlesBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 84-byte inline buffer (no managed string on the wire). spec: packets/2-70_carrier_pigeon_send.yaml</summary>
    [InlineArray(84)]
    public struct MessageBodyBuffer
    {
        private byte _element0;
    }

}
