// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-56_stall_enter.yaml
//   spec: packets/2-56_stall_enter.yaml
//   opcode: 0x20038   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client request to enter / open a selected stall from the personal-stall market list. A fixed 4-byte body carrying the selected stall row's stored id. Issued by the StallListPanel's ENTER action and the row double-click, with the id taken from the selected row record.
/// Wire layout per <c>packets/2-56_stall_enter.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgStallEnter
{
    /// <summary>The opcode value for this message. spec: packets/2-56_stall_enter.yaml</summary>
    public const uint OpcodeId = 0x20038;

    /// <summary>Declared wire size in bytes (spec: packets/2-56_stall_enter.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgStallEnter&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint StallId;
}
