// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-100_npc_open_req.yaml
//   spec: packets/2-100_npc_open_req.yaml
//   opcode: 0x20064   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// One-byte "request open NPC panel" round-trip for the service NPC whose descriptor KIND byte is 0x19 (25). Instead of opening a pre-built panel locally, this NPC kind asks the server to open the panel; the body is a single byte.
/// Wire layout per <c>packets/2-100_npc_open_req.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcOpenReq
{
    /// <summary>The opcode value for this message. spec: packets/2-100_npc_open_req.yaml</summary>
    public const uint OpcodeId = 0x20064;

    /// <summary>Declared wire size in bytes (spec: packets/2-100_npc_open_req.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcOpenReq&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Request;
}
