// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-57_stack_distribute.yaml
//   spec: packets/2-57_stack_distribute.yaml
//   opcode: 0x20039   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Stack split / distribute submit. Distributes/splits a stack across the matching slots of an item the player owns, with an affordability cap. A fixed 20-byte header followed by an OPTIONAL u8 tail of contributing-slot indices (one byte per slot), appended only when op_type==1 and the count is nonzero.
/// Wire layout per <c>packets/2-57_stack_distribute.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgStackDistribute
{
    /// <summary>The opcode value for this message. spec: packets/2-57_stack_distribute.yaml</summary>
    public const uint OpcodeId = 0x20039;

    public byte OpType;
    public byte SourceIndex;
    public byte DestSlot;
    public Pad0Buffer Pad0;
    public ushort Quantity;
    public uint ValueA;
    public uint ValueB;
    public byte TailCount;
    public Pad1Buffer Pad1;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-57_stack_distribute.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-57_stack_distribute.yaml</summary>
    [InlineArray(3)]
    public struct Pad1Buffer
    {
        private byte _element0;
    }

}
