// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-123_gift_char_receive.yaml
//   spec: packets/2-123_gift_char_receive.yaml
//   opcode: 0x2007b   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-123_gift_char_receive.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGiftCharReceiveConfirm
{
    /// <summary>The opcode value for this message. spec: packets/2-123_gift_char_receive.yaml</summary>
    public const uint OpcodeId = 0x2007b;

    /// <summary>Declared wire size in bytes (spec: packets/2-123_gift_char_receive.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGiftCharReceiveConfirm&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public byte AcceptFlag;
    public uint OfferId;
    public byte SubField;
    public Pad06Buffer Pad06;

    /// <summary>Fixed 6-byte inline buffer (no managed string on the wire). spec: packets/2-123_gift_char_receive.yaml</summary>
    [InlineArray(6)]
    public struct Pad06Buffer
    {
        private byte _element0;
    }

}
