// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-23_trade_request.yaml
//   spec: packets/2-23_trade_request.yaml
//   opcode: 0x20017   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client player-to-player trade request / response. Carries a 1-byte mode selector and a 4-byte actor id. Started from the right-click target "trade" menu; the server replies with 4/23 TradeRequestResult.
/// Wire layout per <c>packets/2-23_trade_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgTradeRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-23_trade_request.yaml</summary>
    public const uint OpcodeId = 0x20017;

    /// <summary>Declared wire size in bytes (spec: packets/2-23_trade_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgTradeRequest&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte Mode;
    public Pad0Buffer Pad0;
    public uint Value;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-23_trade_request.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
