// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-20_npc_sell.yaml
//   spec: packets/2-20_npc_sell.yaml
//   opcode: 0x20014   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Sell one inventory item to an NPC merchant. Emitted from the inventory/merchant flow when the player confirms a sale. The server replies with S2C 4/20 SmsgNpcSellItemAck. Reconfirmed in HUD-II Wave 3: the 12-byte body layout is recovered (leading id, two selector bytes, a 2-byte gap, trailing quantity word).
/// Wire layout per <c>packets/2-20_npc_sell.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcSell
{
    /// <summary>The opcode value for this message. spec: packets/2-20_npc_sell.yaml</summary>
    public const uint OpcodeId = 0x20014;

    /// <summary>Declared wire size in bytes (spec: packets/2-20_npc_sell.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcSell&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public uint Id;
    public byte SlotMode;
    public byte SubSel;
    public ReservedBuffer Reserved;
    public uint Quantity;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-20_npc_sell.yaml</summary>
    [InlineArray(2)]
    public struct ReservedBuffer
    {
        private byte _element0;
    }

}
