// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-47_hud_code_value.yaml
//   spec: packets/2-47_hud_code_value.yaml
//   opcode: 0x2002f   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Simple (code, value) HUD action. A leading mode/sub-action byte, a 3-byte alignment gap, then a target/amount u32. Gated only by the panel-modal guard (no list lookup). Sibling shape to 2/48.
/// Wire layout per <c>packets/2-47_hud_code_value.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHudCodeValue
{
    /// <summary>The opcode value for this message. spec: packets/2-47_hud_code_value.yaml</summary>
    public const uint OpcodeId = 0x2002f;

    /// <summary>Declared wire size in bytes (spec: packets/2-47_hud_code_value.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHudCodeValue&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte Code;
    public Pad0Buffer Pad0;
    public uint Value;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-47_hud_code_value.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
