// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-153_pet_summon.yaml
//   spec: packets/2-153_pet_summon.yaml
//   opcode: 0x20099   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Pet/mount summon or dismiss. Client-side 60-second cooldown between summon attempts.
/// Wire layout per <c>packets/2-153_pet_summon.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPetSummon
{
    /// <summary>The opcode value for this message. spec: packets/2-153_pet_summon.yaml</summary>
    public const uint OpcodeId = 0x20099;

    /// <summary>Declared wire size in bytes (spec: packets/2-153_pet_summon.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPetSummon&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public byte Mode;
    public byte Param1;
    public byte SlotFlag;
    public byte NpcSlot;
}
