// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-83_chat_contextual.yaml
//   spec: packets/2-83_chat_contextual.yaml
//   opcode: 0x20053   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client chat with a 24-byte context header (sender/target/channel metadata), followed by a length-prefixed text body. Used for contextual chat routing distinct from the 2/7 whisper and 3/21 channel forms.
/// Wire layout per <c>packets/2-83_chat_contextual.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgChatContextual
{
    /// <summary>The opcode value for this message. spec: packets/2-83_chat_contextual.yaml</summary>
    public const uint OpcodeId = 0x20053;

    public ContextHeaderBuffer ContextHeader;

    /// <summary>Fixed 24-byte inline buffer (no managed string on the wire). spec: packets/2-83_chat_contextual.yaml</summary>
    [InlineArray(24)]
    public struct ContextHeaderBuffer
    {
        private byte _element0;
    }

}
