// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-124_item_panel_flag.yaml
//   spec: packets/2-124_item_panel_flag.yaml
//   opcode: 0x2007c   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Item-panel single-byte flag / toggle action. A single selection/flag byte emitted from the item-panel event handler.
/// Wire layout per <c>packets/2-124_item_panel_flag.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgItemPanelFlag
{
    /// <summary>The opcode value for this message. spec: packets/2-124_item_panel_flag.yaml</summary>
    public const uint OpcodeId = 0x2007c;

    /// <summary>Declared wire size in bytes (spec: packets/2-124_item_panel_flag.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgItemPanelFlag&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Flag;
}
