// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-42_context_action.yaml
//   spec: packets/2-42_context_action.yaml
//   opcode: 0x2002a   direction: C2S   size: 44
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Submit a 44-byte context-action record (11 u32 + tail) from a HUD list/panel on a context object. A leading mode/discriminator byte selects an optional confirmation-tooltip path; the same context object also raises the 2/35 party-op. Width corroborated by two independent callers.
/// Wire layout per <c>packets/2-42_context_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgContextAction
{
    /// <summary>The opcode value for this message. spec: packets/2-42_context_action.yaml</summary>
    public const uint OpcodeId = 0x2002a;

    /// <summary>Declared wire size in bytes (spec: packets/2-42_context_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgContextAction&gt;() == 44</c> in a test.</summary>
    public const int Size = 44;

    public byte Mode;
    public Rest0Buffer Rest0;
    public WordsBuffer Words;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-42_context_action.yaml</summary>
    [InlineArray(3)]
    public struct Rest0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 40-byte inline buffer (no managed string on the wire). spec: packets/2-42_context_action.yaml</summary>
    [InlineArray(40)]
    public struct WordsBuffer
    {
        private byte _element0;
    }

}
