// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-113_repair_commit.yaml
//   spec: packets/2-113_repair_commit.yaml
//   opcode: 0x20071   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Item repair/refine commit sent at a repair NPC (descriptor KIND 0xE) after the player confirms a repair entry. The client runs a gold / eligibility / capacity pre-check before sending. The send arguments observed are the active target field and the selected list index.
/// Wire layout per <c>packets/2-113_repair_commit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgRepairCommit
{
    /// <summary>The opcode value for this message. spec: packets/2-113_repair_commit.yaml</summary>
    public const uint OpcodeId = 0x20071;

    public uint TargetId;
    public uint SelIndex;
}
