// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-44_item_quick_move.yaml
//   spec: packets/2-44_item_quick_move.yaml
//   opcode: 0x2002c   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client item quick-move / shift-transfer -- the shared item-model "quick move" send that moves an item to-or-from a container in one shortcut action (no held-item drag). A fixed 12-byte body with the same shape as the plain move (2/46): a leading mode/selector and container/slot parameters plus a context word. The storage ("keep") grid uses it to quick-transfer items into / out of its 60-cell storage grid.
/// Wire layout per <c>packets/2-44_item_quick_move.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgItemQuickMove
{
    /// <summary>The opcode value for this message. spec: packets/2-44_item_quick_move.yaml</summary>
    public const uint OpcodeId = 0x2002c;

    /// <summary>Declared wire size in bytes (spec: packets/2-44_item_quick_move.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgItemQuickMove&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public byte Mode;
    public byte B1;
    public byte B2;
    public byte B3;
    public byte B4;
    public byte B5;
    public Pad0Buffer Pad0;
    public uint Context;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-44_item_quick_move.yaml</summary>
    [InlineArray(2)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
