// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-54_friend_list_refresh.yaml
//   spec: packets/2-54_friend_list_refresh.yaml
//   opcode: 0x20036   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client request to refresh the friend list / online-status. A 1-byte send raised by the friend window's refresh control. The send path is rate-limited client-side (a 3-minute throttle) so it cannot be spammed.
/// Wire layout per <c>packets/2-54_friend_list_refresh.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgFriendListRefresh
{
    /// <summary>The opcode value for this message. spec: packets/2-54_friend_list_refresh.yaml</summary>
    public const uint OpcodeId = 0x20036;

    /// <summary>Declared wire size in bytes (spec: packets/2-54_friend_list_refresh.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgFriendListRefresh&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Flag;
}
