// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-61_party_request_union.yaml
//   spec: packets/2-61_party_request_union.yaml
//   opcode: 0x2003d   direction: C2S   size: 36
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Party operations request — create / invite / disband / leave keyed by a leading action subcode; one path is a guild-fame donation carrying a name + amount. A fixed 36-byte discriminated union. Driven by the Guild/Party "A" panel and the social re-ask confirm panel.
/// Wire layout per <c>packets/2-61_party_request_union.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPartyRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-61_party_request_union.yaml</summary>
    public const uint OpcodeId = 0x2003d;

    /// <summary>Declared wire size in bytes (spec: packets/2-61_party_request_union.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPartyRequest&gt;() == 36</c> in a test.</summary>
    public const int Size = 36;

    public byte Subcode;
    public byte SubFlag;
    public Reserved0Buffer Reserved0;
    public uint ContextId;
    public AmountQBuffer AmountQ;
    public NameBuffer Name;
    public TailBuffer Tail;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-61_party_request_union.yaml</summary>
    [InlineArray(2)]
    public struct Reserved0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 8-byte inline buffer (no managed string on the wire). spec: packets/2-61_party_request_union.yaml</summary>
    [InlineArray(8)]
    public struct AmountQBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-61_party_request_union.yaml</summary>
    [InlineArray(17)]
    public struct NameBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-61_party_request_union.yaml</summary>
    [InlineArray(3)]
    public struct TailBuffer
    {
        private byte _element0;
    }

}
