// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-103_text_form_submit.yaml
//   spec: packets/2-103_text_form_submit.yaml
//   opcode: 0x20067   direction: C2S   size: 196
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-103_text_form_submit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgTextFormSubmit4
{
    /// <summary>The opcode value for this message. spec: packets/2-103_text_form_submit.yaml</summary>
    public const uint OpcodeId = 0x20067;

    /// <summary>Declared wire size in bytes (spec: packets/2-103_text_form_submit.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgTextFormSubmit4&gt;() == 196</c> in a test.</summary>
    public const int Size = 196;

    public Line0Buffer Line0;
    public Line1Buffer Line1;
    public Line2Buffer Line2;
    public Line3Buffer Line3;

    /// <summary>Fixed 49-byte inline buffer (no managed string on the wire). spec: packets/2-103_text_form_submit.yaml</summary>
    [InlineArray(49)]
    public struct Line0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 49-byte inline buffer (no managed string on the wire). spec: packets/2-103_text_form_submit.yaml</summary>
    [InlineArray(49)]
    public struct Line1Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 49-byte inline buffer (no managed string on the wire). spec: packets/2-103_text_form_submit.yaml</summary>
    [InlineArray(49)]
    public struct Line2Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 49-byte inline buffer (no managed string on the wire). spec: packets/2-103_text_form_submit.yaml</summary>
    [InlineArray(49)]
    public struct Line3Buffer
    {
        private byte _element0;
    }

}
