// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-93_revenge_vote.yaml
//   spec: packets/2-93_revenge_vote.yaml
//   opcode: 0x2005d   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-93_revenge_vote.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgRevengeVote
{
    /// <summary>The opcode value for this message. spec: packets/2-93_revenge_vote.yaml</summary>
    public const uint OpcodeId = 0x2005d;

    /// <summary>Declared wire size in bytes (spec: packets/2-93_revenge_vote.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgRevengeVote&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte VoteFlag;
}
