// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-62_relation_named_request.yaml
//   spec: packets/2-62_relation_named_request.yaml
//   opcode: 0x2003e   direction: C2S   size: 19
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// A name-keyed relation/party request carrying a 16-byte character name plus a type word and a flag byte. A thin send from the social confirm panel after selecting a named target.
/// Wire layout per <c>packets/2-62_relation_named_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgRelationNamedRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-62_relation_named_request.yaml</summary>
    public const uint OpcodeId = 0x2003e;

    /// <summary>Declared wire size in bytes (spec: packets/2-62_relation_named_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgRelationNamedRequest&gt;() == 19</c> in a test.</summary>
    public const int Size = 19;

    public NameBuffer Name;
    public ushort Type;
    public byte Flag;

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/2-62_relation_named_request.yaml</summary>
    [InlineArray(16)]
    public struct NameBuffer
    {
        private byte _element0;
    }

}
