// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-74_stall_list_request.yaml
//   spec: packets/2-74_stall_list_request.yaml
//   opcode: 0x2004a   direction: C2S   size: 32
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client request / search of the personal-stall (player-vendor) market list. A fixed 32-byte body carrying a leading flag/mode byte, a 30-character CP949 name-filter string, and one trailing byte. Issued by the StallListPanel's search-submit and refresh actions; an empty filter requests the full ("all") list.
/// Wire layout per <c>packets/2-74_stall_list_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgStallListRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-74_stall_list_request.yaml</summary>
    public const uint OpcodeId = 0x2004a;

    /// <summary>Declared wire size in bytes (spec: packets/2-74_stall_list_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgStallListRequest&gt;() == 32</c> in a test.</summary>
    public const int Size = 32;

    public byte Flag;
    public NameBuffer Name;
    public byte Tail;

    /// <summary>Fixed 30-byte inline buffer (no managed string on the wire). spec: packets/2-74_stall_list_request.yaml</summary>
    [InlineArray(30)]
    public struct NameBuffer
    {
        private byte _element0;
    }

}
