// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-10000_keepalive.yaml
//   spec: packets/2-10000_keepalive.yaml
//   opcode: 0x22710   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client keepalive / ping. A dedicated background thread sends this roughly every 20 seconds while the game connection is up and not suppressed. The payload is a 4-byte zero body. It is the only major-2 (GameAction) message in this catalog that is server-bound on a timer rather than a user action, and it follows a special send path -- compressed only, NOT re-encrypted.
/// Wire layout per <c>packets/2-10000_keepalive.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgKeepalive
{
    /// <summary>The opcode value for this message. spec: packets/2-10000_keepalive.yaml</summary>
    public const uint OpcodeId = 0x22710;

    /// <summary>Declared wire size in bytes (spec: packets/2-10000_keepalive.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgKeepalive&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint Padding;
}
