// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-52_use_skill.yaml
//   spec: packets/2-52_use_skill.yaml
//   opcode: 0x20034   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client skill-activate / battle-action request. A 24-byte header (skill slot + aim) followed by two optional arrays of target actor ids. Basic melee is the same opcode with SkillSlot=0xFF and both counts 0. The server replies with the S2C 5/52 ActorSkillAction broadcast.
/// Wire layout per <c>packets/2-52_use_skill.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgUseSkill
{
    /// <summary>The opcode value for this message. spec: packets/2-52_use_skill.yaml</summary>
    public const uint OpcodeId = 0x20034;

    public byte SkillSlot;
    public byte Selector;
    public Pad0Buffer Pad0;
    public uint AimMode;
    public float AimScale;
    public float AimX;
    public float AimZ;
    public ushort CountA;
    public ushort CountB;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-52_use_skill.yaml</summary>
    [InlineArray(2)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
