// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-5_actor_interaction.yaml
//   spec: packets/2-5_actor_interaction.yaml
//   opcode: 0x20005   direction: C2S   size: 28
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// NPC / actor service-menu interaction request (the generic "I selected this menu option on this actor/NPC"). Carries a select-mode byte, a sub-index, a class/flag byte, the target actor id, and (for name-keyed options) a 17-byte CP949 name. Used across the service-NPC menu and a context-menu dispatcher.
/// Wire layout per <c>packets/2-5_actor_interaction.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgActorInteraction
{
    /// <summary>The opcode value for this message. spec: packets/2-5_actor_interaction.yaml</summary>
    public const uint OpcodeId = 0x20005;

    /// <summary>Declared wire size in bytes (spec: packets/2-5_actor_interaction.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgActorInteraction&gt;() == 28</c> in a test.</summary>
    public const int Size = 28;

    public byte SelectMode;
    public byte SubIndex;
    public byte ClassOrFlag;
    public byte Reserved0;
    public uint TargetActorId;
    public FlagsBuffer Flags;
    public NameBuffer Name;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-5_actor_interaction.yaml</summary>
    [InlineArray(3)]
    public struct FlagsBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-5_actor_interaction.yaml</summary>
    [InlineArray(17)]
    public struct NameBuffer
    {
        private byte _element0;
    }

}
