// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-110_quest_npc_step.yaml
//   spec: packets/2-110_quest_npc_step.yaml
//   opcode: 0x2006e   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Quest-NPC step request emitted by the quest-NPC panel (NPC descriptor KIND 0xA). A 4-byte body whose leading "mode" byte is derived from the NPC's current quest phase. This is distinct from the general quest-action message (2/28).
/// Wire layout per <c>packets/2-110_quest_npc_step.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgQuestNpcStep
{
    /// <summary>The opcode value for this message. spec: packets/2-110_quest_npc_step.yaml</summary>
    public const uint OpcodeId = 0x2006e;

    /// <summary>Declared wire size in bytes (spec: packets/2-110_quest_npc_step.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgQuestNpcStep&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public byte Mode;
    public byte ArgA;
    public byte ArgB;
    public byte ArgC;
}
