// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-80_guild_request_union.yaml
//   spec: packets/2-80_guild_request_union.yaml
//   opcode: 0x20050   direction: C2S   size: 48
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Guild / clan operations request — create, join, leave, disband, accept, reject, fame-donate, plus a map/territory object-pick variant. A fixed 48-byte discriminated union keyed by a leading action subcode. Driven by guild fame/management panels and a world-map region click.
/// Wire layout per <c>packets/2-80_guild_request_union.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGuildRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-80_guild_request_union.yaml</summary>
    public const uint OpcodeId = 0x20050;

    /// <summary>Declared wire size in bytes (spec: packets/2-80_guild_request_union.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGuildRequest&gt;() == 48</c> in a test.</summary>
    public const int Size = 48;

    public byte Subcode;
    public Pad0Buffer Pad0;
    public uint ContextId;
    public AmountQBuffer AmountQ;
    public UnionBuffer Union;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-80_guild_request_union.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 8-byte inline buffer (no managed string on the wire). spec: packets/2-80_guild_request_union.yaml</summary>
    [InlineArray(8)]
    public struct AmountQBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 32-byte inline buffer (no managed string on the wire). spec: packets/2-80_guild_request_union.yaml</summary>
    [InlineArray(32)]
    public struct UnionBuffer
    {
        private byte _element0;
    }

}
