// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-72_gm_command.yaml
//   spec: packets/2-72_gm_command.yaml
//   opcode: 0x20048   direction: C2S   size: 32
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// GM tool panel administrative command. Carries a mode selector, a 16-byte CP949 target name, and three numeric parameters parsed from the GM input fields.
/// Wire layout per <c>packets/2-72_gm_command.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGmCommand
{
    /// <summary>The opcode value for this message. spec: packets/2-72_gm_command.yaml</summary>
    public const uint OpcodeId = 0x20048;

    /// <summary>Declared wire size in bytes (spec: packets/2-72_gm_command.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGmCommand&gt;() == 32</c> in a test.</summary>
    public const int Size = 32;

    public byte Mode;
    public TargetNameBuffer TargetName;
    public PaddingBuffer Padding;
    public uint Param1;
    public float Param2;
    public float Param3;

    /// <summary>Fixed 16-byte inline buffer (no managed string on the wire). spec: packets/2-72_gm_command.yaml</summary>
    [InlineArray(16)]
    public struct TargetNameBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-72_gm_command.yaml</summary>
    [InlineArray(3)]
    public struct PaddingBuffer
    {
        private byte _element0;
    }

}
