// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-37_party_leader_op.yaml
//   spec: packets/2-37_party_leader_op.yaml
//   opcode: 0x20025   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client party leader / transfer operation. Carries a 1-byte mode selector and a 4-byte target actor id. Believed to drive a leader-transfer or role toggle from the party panel context menu; the matching server result is folded into the 4/37 PartyLeaderActionResult family.
/// Wire layout per <c>packets/2-37_party_leader_op.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPartyLeaderOp
{
    /// <summary>The opcode value for this message. spec: packets/2-37_party_leader_op.yaml</summary>
    public const uint OpcodeId = 0x20025;

    /// <summary>Declared wire size in bytes (spec: packets/2-37_party_leader_op.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPartyLeaderOp&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte Mode;
    public Pad0Buffer Pad0;
    public uint TargetId;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-37_party_leader_op.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
