// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-107_amount_commit.yaml
//   spec: packets/2-107_amount_commit.yaml
//   opcode: 0x2006b   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Commit a numeric amount entered digit-by-digit on a keypad. A single u32 holding the final accumulated amount (e.g. an amount to bet/deposit/buy).
/// Wire layout per <c>packets/2-107_amount_commit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgAmountCommit
{
    /// <summary>The opcode value for this message. spec: packets/2-107_amount_commit.yaml</summary>
    public const uint OpcodeId = 0x2006b;

    /// <summary>Declared wire size in bytes (spec: packets/2-107_amount_commit.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgAmountCommit&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public uint Amount;
}
