// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-84_npc_mediated_name_request.yaml
//   spec: packets/2-84_npc_mediated_name_request.yaml
//   opcode: 0x20054   direction: C2S   size: 19
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// A throttled, name-targeted service request that requires a specific NPC (world-type 1028) in range — consistent with a petition / report / guard-or-official interaction against a named player. A category byte, a nearby-NPC index, and a 17-byte CP949 name. Client-throttled to once per 30 seconds.
/// Wire layout per <c>packets/2-84_npc_mediated_name_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgNpcMediatedNameRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-84_npc_mediated_name_request.yaml</summary>
    public const uint OpcodeId = 0x20054;

    /// <summary>Declared wire size in bytes (spec: packets/2-84_npc_mediated_name_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgNpcMediatedNameRequest&gt;() == 19</c> in a test.</summary>
    public const int Size = 19;

    public byte Kind;
    public byte NearbyNpcIdx;
    public NameBuffer Name;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-84_npc_mediated_name_request.yaml</summary>
    [InlineArray(17)]
    public struct NameBuffer
    {
        private byte _element0;
    }

}
