// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-16_actor_interact_mode100.yaml
//   spec: packets/2-16_actor_interact_mode100.yaml
//   opcode: 0x20010   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Actor/NPC interaction request carrying an interaction mode plus several sub-byte parameters and a u32 actor id / numeric argument. One caller hard-codes mode=100 (the NPC-open mode used elsewhere); a second caller carries a six-parameter action.
/// Wire layout per <c>packets/2-16_actor_interact_mode100.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgActorInteractMode100
{
    /// <summary>The opcode value for this message. spec: packets/2-16_actor_interact_mode100.yaml</summary>
    public const uint OpcodeId = 0x20010;

    /// <summary>Declared wire size in bytes (spec: packets/2-16_actor_interact_mode100.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgActorInteractMode100&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public byte Mode;
    public byte B1;
    public byte B2;
    public byte B3;
    public byte B4;
    public Pad0Buffer Pad0;
    public uint ActorOrArg;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-16_actor_interact_mode100.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
