// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-7_whisper.yaml
//   spec: packets/2-7_whisper.yaml
//   opcode: 0x20007   direction: C2S   size: var
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-7_whisper.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgChat
{
    /// <summary>The opcode value for this message. spec: packets/2-7_whisper.yaml</summary>
    public const uint OpcodeId = 0x20007;

    public byte Channel;
    public byte Selector;
    public TargetNameBuffer TargetName;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-7_whisper.yaml</summary>
    [InlineArray(17)]
    public struct TargetNameBuffer
    {
        private byte _element0;
    }

}
