// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-151_product_buy.yaml
//   spec: packets/2-151_product_buy.yaml
//   opcode: 0x20097   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// The product / crafting panel's ONLY network send. A 1-byte selector body: the panel sends this once on open/refresh (selector 0) to ask the server for the current production list/money, and again on the tip-panel confirm action (selector 200 / 0xC8). All tab and page navigation inside the panel are LOCAL repaints over a server-pushed recipe list -- they are not network sends. The list/money refresh arrives inbound on S2C 3/8.
/// Wire layout per <c>packets/2-151_product_buy.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgProductBuy
{
    /// <summary>The opcode value for this message. spec: packets/2-151_product_buy.yaml</summary>
    public const uint OpcodeId = 0x20097;

    /// <summary>Declared wire size in bytes (spec: packets/2-151_product_buy.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgProductBuy&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Selector;
}
