// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-58_priced_commit.yaml
//   spec: packets/2-58_priced_commit.yaml
//   opcode: 0x2003a   direction: C2S   size: 24
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Priced HUD purchase/commit on a slot. The sender first runs an affordability check (amount x unit-price vs the player's gold) using a slot-indexed unit-price table, then blits a 24-byte record. Sibling of the 16/32-byte HUD record submits (2/50, 2/55) in the same panel cluster — this one is the priced variant.
/// Wire layout per <c>packets/2-58_priced_commit.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPricedCommit
{
    /// <summary>The opcode value for this message. spec: packets/2-58_priced_commit.yaml</summary>
    public const uint OpcodeId = 0x2003a;

    /// <summary>Declared wire size in bytes (spec: packets/2-58_priced_commit.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPricedCommit&gt;() == 24</c> in a test.</summary>
    public const int Size = 24;

    public HeaderBuffer Header;
    public byte SlotIndex;
    public Pad0Buffer Pad0;
    public uint Amount;
    public RecordTailBuffer RecordTail;

    /// <summary>Fixed 4-byte inline buffer (no managed string on the wire). spec: packets/2-58_priced_commit.yaml</summary>
    [InlineArray(4)]
    public struct HeaderBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-58_priced_commit.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 12-byte inline buffer (no managed string on the wire). spec: packets/2-58_priced_commit.yaml</summary>
    [InlineArray(12)]
    public struct RecordTailBuffer
    {
        private byte _element0;
    }

}
