// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-143_playtime_action.yaml
//   spec: packets/2-143_playtime_action.yaml
//   opcode: 0x2008f   direction: C2S   size: 4
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Playtime reward panel action. Opens/refreshes the playtime panel or claims a reward item depending on Mode.
/// Wire layout per <c>packets/2-143_playtime_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPlaytimeAction
{
    /// <summary>The opcode value for this message. spec: packets/2-143_playtime_action.yaml</summary>
    public const uint OpcodeId = 0x2008f;

    /// <summary>Declared wire size in bytes (spec: packets/2-143_playtime_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPlaytimeAction&gt;() == 4</c> in a test.</summary>
    public const int Size = 4;

    public byte Mode;
    public byte SlotOrFlag;
    public byte Param1;
    public byte Param2;
}
