// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-39_hud_context_action.yaml
//   spec: packets/2-39_hud_context_action.yaml
//   opcode: 0x20027   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-39_hud_context_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHudContextAction39
{
    /// <summary>The opcode value for this message. spec: packets/2-39_hud_context_action.yaml</summary>
    public const uint OpcodeId = 0x20027;

    /// <summary>Declared wire size in bytes (spec: packets/2-39_hud_context_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHudContextAction39&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public PrefixBuffer Prefix;
    public byte CodeA;
    public byte CodeB;
    public byte CodeC;
    public TailBuffer Tail;

    /// <summary>Fixed 6-byte inline buffer (no managed string on the wire). spec: packets/2-39_hud_context_action.yaml</summary>
    [InlineArray(6)]
    public struct PrefixBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-39_hud_context_action.yaml</summary>
    [InlineArray(3)]
    public struct TailBuffer
    {
        private byte _element0;
    }

}
