// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-76_fate_interaction.yaml
//   spec: packets/2-76_fate_interaction.yaml
//   opcode: 0x2004c   direction: C2S   size: 20
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Fate/destiny NPC interaction. Carries a fate state selector, a slot index, a 17-byte CP949 target name, and an item list index.
/// Wire layout per <c>packets/2-76_fate_interaction.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgFateInteraction
{
    /// <summary>The opcode value for this message. spec: packets/2-76_fate_interaction.yaml</summary>
    public const uint OpcodeId = 0x2004c;

    /// <summary>Declared wire size in bytes (spec: packets/2-76_fate_interaction.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgFateInteraction&gt;() == 20</c> in a test.</summary>
    public const int Size = 20;

    public byte FateState;
    public byte SlotIndex;
    public ActorNameBuffer ActorName;
    public byte ItemListIndex;

    /// <summary>Fixed 17-byte inline buffer (no managed string on the wire). spec: packets/2-76_fate_interaction.yaml</summary>
    [InlineArray(17)]
    public struct ActorNameBuffer
    {
        private byte _element0;
    }

}
