// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-22_service_list_action.yaml
//   spec: packets/2-22_service_list_action.yaml
//   opcode: 0x20016   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// HUD-list / actor service action (same family as 2/16/2/17/2/21, distinct selector). Carries a u32 mode/flag, an actor/list index byte resolved to an actor id, and trailing status bytes. The caller validates the resolved actor before sending.
/// Wire layout per <c>packets/2-22_service_list_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgServiceListAction
{
    /// <summary>The opcode value for this message. spec: packets/2-22_service_list_action.yaml</summary>
    public const uint OpcodeId = 0x20016;

    /// <summary>Declared wire size in bytes (spec: packets/2-22_service_list_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgServiceListAction&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint Mode;
    public byte ActorIndex;
    public TailBuffer Tail;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-22_service_list_action.yaml</summary>
    [InlineArray(3)]
    public struct TailBuffer
    {
        private byte _element0;
    }

}
