// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-41_hud_select.yaml
//   spec: packets/2-41_hud_select.yaml
//   opcode: 0x20029   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Confirm / submit a three-key selection from a HUD list. Three contiguous u32 keys, gated by a slot-bound check and a resolver+sentinel gate.
/// Wire layout per <c>packets/2-41_hud_select.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHudSelect
{
    /// <summary>The opcode value for this message. spec: packets/2-41_hud_select.yaml</summary>
    public const uint OpcodeId = 0x20029;

    /// <summary>Declared wire size in bytes (spec: packets/2-41_hud_select.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHudSelect&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public uint KeyA;
    public uint KeyB;
    public uint KeyC;
}
