// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-122_gift_char_send.yaml
//   spec: packets/2-122_gift_char_send.yaml
//   opcode: 0x2007a   direction: C2S   size: 12
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-122_gift_char_send.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGiftCharSend
{
    /// <summary>The opcode value for this message. spec: packets/2-122_gift_char_send.yaml</summary>
    public const uint OpcodeId = 0x2007a;

    /// <summary>Declared wire size in bytes (spec: packets/2-122_gift_char_send.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGiftCharSend&gt;() == 12</c> in a test.</summary>
    public const int Size = 12;

    public uint TargetId;
    public byte GroupByte;
    public CodeBuffer Code;
    public byte CodeNul;
    public Pad0ABuffer Pad0A;

    /// <summary>Fixed 4-byte inline buffer (no managed string on the wire). spec: packets/2-122_gift_char_send.yaml</summary>
    [InlineArray(4)]
    public struct CodeBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-122_gift_char_send.yaml</summary>
    [InlineArray(2)]
    public struct Pad0ABuffer
    {
        private byte _element0;
    }

}
