// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-65_guild_context_ack.yaml
//   spec: packets/2-65_guild_context_ack.yaml
//   opcode: 0x20041   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// A reactive 1-byte context ack / refresh. Raised event-driven from several S2C handlers (the per-tick game-state handler, the guild-member-remove result) and from guild/social panel context resolution — an auto-reply / state-confirm, not a single UI button.
/// Wire layout per <c>packets/2-65_guild_context_ack.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgGuildContextAck
{
    /// <summary>The opcode value for this message. spec: packets/2-65_guild_context_ack.yaml</summary>
    public const uint OpcodeId = 0x20041;

    /// <summary>Declared wire size in bytes (spec: packets/2-65_guild_context_ack.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgGuildContextAck&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte Selector;
}
