// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-137_exit_notify.yaml
//   spec: packets/2-137_exit_notify.yaml
//   opcode: 0x20089   direction: C2S   size: 16
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client exit/quit notification, sent when GameState==4. Carries the exit mode, coordinate pair (always zero), and padding.
/// Wire layout per <c>packets/2-137_exit_notify.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgExitNotify
{
    /// <summary>The opcode value for this message. spec: packets/2-137_exit_notify.yaml</summary>
    public const uint OpcodeId = 0x20089;

    /// <summary>Declared wire size in bytes (spec: packets/2-137_exit_notify.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgExitNotify&gt;() == 16</c> in a test.</summary>
    public const int Size = 16;

    public byte Mode;
    public byte Flag;
    public ushort Reserved;
    public float CoordX;
    public float CoordY;
    public byte Extra;
    public PaddingBuffer Padding;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-137_exit_notify.yaml</summary>
    [InlineArray(3)]
    public struct PaddingBuffer
    {
        private byte _element0;
    }

}
