// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-64_class_change_request.yaml
//   spec: packets/2-64_class_change_request.yaml
//   opcode: 0x20040   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Class change / promotion request (select target class + confirm), gated by level/exp/gold tables. Two u32 — a class selector and a param.
/// Wire layout per <c>packets/2-64_class_change_request.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgClassChangeRequest
{
    /// <summary>The opcode value for this message. spec: packets/2-64_class_change_request.yaml</summary>
    public const uint OpcodeId = 0x20040;

    /// <summary>Declared wire size in bytes (spec: packets/2-64_class_change_request.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgClassChangeRequest&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public uint ClassSelector;
    public uint Param;
}
