// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-45_hud_flags_target.yaml
//   spec: packets/2-45_hud_flags_target.yaml
//   opcode: 0x2002d   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// HUD action carrying four flag bytes and a target/slot id. Gated on a MainWindow state flag and an inventory prerequisite (an inventory/slot-id lookup); aborts with a chat notice if a trade is busy.
/// Wire layout per <c>packets/2-45_hud_flags_target.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgHudFlagsTarget
{
    /// <summary>The opcode value for this message. spec: packets/2-45_hud_flags_target.yaml</summary>
    public const uint OpcodeId = 0x2002d;

    /// <summary>Declared wire size in bytes (spec: packets/2-45_hud_flags_target.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgHudFlagsTarget&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte B0;
    public byte B1;
    public byte B2;
    public byte B3;
    public uint Value;
}
