// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-17_service_action.yaml
//   spec: packets/2-17_service_action.yaml
//   opcode: 0x20011   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// HUD-panel actor service request (same NPC/actor interaction family as 2/16, a different action selector). Carries a sub-mode byte, an action-mode byte, and a u32 actor id / argument. The caller keeps a per-instance relink counter, so it is a stateful service interaction.
/// Wire layout per <c>packets/2-17_service_action.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgServiceAction
{
    /// <summary>The opcode value for this message. spec: packets/2-17_service_action.yaml</summary>
    public const uint OpcodeId = 0x20011;

    /// <summary>Declared wire size in bytes (spec: packets/2-17_service_action.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgServiceAction&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte B0;
    public byte Mode;
    public Pad0Buffer Pad0;
    public uint Arg;

    /// <summary>Fixed 2-byte inline buffer (no managed string on the wire). spec: packets/2-17_service_action.yaml</summary>
    [InlineArray(2)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
