// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-35_party_invite.yaml
//   spec: packets/2-35_party_invite.yaml
//   opcode: 0x20023   direction: C2S   size: 8
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// Client party invite / accept request. Carries a 1-byte mode selector and a 4-byte target actor id. Issued from the right-click target menu and the party panel context menu; the server replies in the 4/35 PartyInviteState / 4/76 PartyAcceptResult family.
/// Wire layout per <c>packets/2-35_party_invite.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgPartyInvite
{
    /// <summary>The opcode value for this message. spec: packets/2-35_party_invite.yaml</summary>
    public const uint OpcodeId = 0x20023;

    /// <summary>Declared wire size in bytes (spec: packets/2-35_party_invite.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgPartyInvite&gt;() == 8</c> in a test.</summary>
    public const int Size = 8;

    public byte Mode;
    public Pad0Buffer Pad0;
    public uint TargetId;

    /// <summary>Fixed 3-byte inline buffer (no managed string on the wire). spec: packets/2-35_party_invite.yaml</summary>
    [InlineArray(3)]
    public struct Pad0Buffer
    {
        private byte _element0;
    }

}
