// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-75_roster_assemble.yaml
//   spec: packets/2-75_roster_assemble.yaml
//   opcode: 0x2004b   direction: C2S   size: 80
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// A roster / party / pet-group assemble request carrying up to 10 actor ids (validated to exist and not exceed a 20-member cap). A fixed 80-byte body: an 8-byte header, a 10-entry actor-id list, and a 32-byte trailing block. Driven by a Goods/roster panel commit.
/// Wire layout per <c>packets/2-75_roster_assemble.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgRosterAssemble
{
    /// <summary>The opcode value for this message. spec: packets/2-75_roster_assemble.yaml</summary>
    public const uint OpcodeId = 0x2004b;

    /// <summary>Declared wire size in bytes (spec: packets/2-75_roster_assemble.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgRosterAssemble&gt;() == 80</c> in a test.</summary>
    public const int Size = 80;

    public HeaderBuffer Header;
    public ActorIdsBuffer ActorIds;
    public TailBuffer Tail;

    /// <summary>Fixed 8-byte inline buffer (no managed string on the wire). spec: packets/2-75_roster_assemble.yaml</summary>
    [InlineArray(8)]
    public struct HeaderBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 40-byte inline buffer (no managed string on the wire). spec: packets/2-75_roster_assemble.yaml</summary>
    [InlineArray(40)]
    public struct ActorIdsBuffer
    {
        private byte _element0;
    }

    /// <summary>Fixed 32-byte inline buffer (no managed string on the wire). spec: packets/2-75_roster_assemble.yaml</summary>
    [InlineArray(32)]
    public struct TailBuffer
    {
        private byte _element0;
    }

}
