// <auto-generated>
//   Generated by the packet-codegen skill from packets/2-126_confirm_dialog_state.yaml
//   spec: packets/2-126_confirm_dialog_state.yaml
//   opcode: 0x2007e   direction: C2S   size: 1
//   CLEAN ROOM: re-implemented from a neutral spec; no decompiler output. Do not edit by hand.
// </auto-generated>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MartialHeroes.Network.Protocol.Packets;

/// <summary>
/// >
/// Wire layout per <c>packets/2-126_confirm_dialog_state.yaml</c>.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct CmsgConfirmDialogState
{
    /// <summary>The opcode value for this message. spec: packets/2-126_confirm_dialog_state.yaml</summary>
    public const uint OpcodeId = 0x2007e;

    /// <summary>Declared wire size in bytes (spec: packets/2-126_confirm_dialog_state.yaml). Verify with <c>Unsafe.SizeOf&lt;CmsgConfirmDialogState&gt;() == 1</c> in a test.</summary>
    public const int Size = 1;

    public byte State;
}
