namespace MartialHeroes.Client.Application.Assets;

public static class LoadResourcePlan
{
    public const string MessageCataloguePath = "data/script/msg.xdb";

    public static readonly string[] BootWorkerPaths =
    [
        "data/script/events.scr",
        "data/script/system_control.scr",
        "data/script/mapsetting.scr",
        "data/script/playtime_reward.scr",
        "data/script/items.scr",
        "data/script/skills.scr",
        "data/script/skillcategory.scr",
        "data/item/items_extra.do",
        "data/script/users.scr",
        "data/script/products.scr",
        "data/script/productcollect.scr",
        "data/script/productrandname.scr",
        "data/script/helps.scr",
        "data/script/npc.scr",
        "data/script/npcs.scr",
        "data/script/repair.scr",
        "data/script/mobs.scr",
        "data/script/repair.scr",
        "data/script/upgradeitems.scr",
        "data/script/quests.scr",
        "data/script/discript.sc",
        "data/script/textcommand.do",
        "data/script/chivalry.scr",
        "data/script/letters.scr",
        "data/script/nicktofame.scr",
        "data/script/guildcrest.scr",
        "data/script/discript.sc",
        "data/script/tiphelp.scr",
        "data/script/setitemname.scr",
        "data/script/oblist.scr",
        "data/script/citems.scr",
        "data/script/Tutor.scr",
        "data/script/warstoneinfo.scr",
        "data/script/statue.scr",
        "data/script/skillneedset.scr",
        "data/script/viplevels.scr",
        "data/script/itemscale.scr",
        "data/script/itemeffect.scr",
        "data/ui/UiTex.txt",
        "data/item/skinlist.txt",
        "data/char/sameemoticon.txt",
        "data/ui/guildicon/crestlist.txt",
        "data/script/effectscale.xdb",
        "data/script/creature_item.xdb",
        "data/script/vehicle.xdb",
        "data/script/buff_icon_position.xdb",
        "data/effect/bmplist.lst",
        "data/effect/xobj.lst",
        "data/effect/xeffect.lst",
        "data/effect/effect.cache",
        "data/effect/totalmugong.txt"
    ];
}